# Site settings
author: Nicole Eidi
title: Web Crawling 
header-img: img/home-bg.png
email: nicoleeidi1@gmail.com
copyright_name: Nicole Eidi
description: > # this means to ignore newlines until "baseurl:"
  A beginner's guide of tricks for learning new frameworks 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  nicoleeidi

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
